### PR TITLE
Activates the LocaleMiddleware

### LINKED ISSUE #35: Respect the Accept-Language header
Validation error messages should be localized in EN/DE. See https://docs.djangoproject.com/en/1.9/ref/middleware/#module-django.middleware.locale

### PR DESCRIPTION
**Pull request by jasinai**
Also tests some response texts

Do **not** merge, needs
- [x] Tivix/django-rest-auth#165 to be merged
- [x] requirements.txt to be updated

Closes #35

### CODE REVIEW

**Comment by audax** [comment]
If they don't merge the PR, we will just have to fork it.

**Comment by audax** [comment]
You can now update the requirements to use the git-master until they create a new release. @jasinai

**Comment by jasinai** [comment]
Yes, I would like to do it, but they ignored the mo-files, so the translation does not work. I opened another [pull request](https://github.com/Tivix/django-rest-auth/pull/178), but I could the commit to the pip file, if you think it is okay for now.

**Comment by audax** [comment]
If phantomjs cannot find the button, why doesn't the test fail?

**Comment by jasinai** [comment]
I think this is only a problem with my german ubuntu.

**Pull request merged**
